syntax = "proto3";

package s2.v1;

option java_multiple_files = true;
option java_package = "s2.v1";

// Position of a record in a stream.
message StreamPosition {
  // Sequence number assigned by the service.
  uint64 seq_num = 1;
  // Timestamp, which may be user-specified or assigned by the service.
  // If it is assigned by the service, it will represent milliseconds since Unix epoch.
  uint64 timestamp = 2;
}

// Headers add structured information to a record as name-value pairs.
message Header {
  // Header name blob.
  // The name cannot be empty, with the exception of an S2 command record.
  bytes name = 1;
  // Header value blob.
  bytes value = 2;
}

// Record to be appended to a stream.
message AppendRecord {
  // Timestamp for this record.
  // Precise semantics depend on the stream's `timestamping` config.
  optional uint64 timestamp = 1;
  // Series of name-value pairs for this record.
  repeated Header headers = 2;
  // Body of this record.
  bytes body = 3;
}

// Storage class for recent writes.
enum StorageClass {
  // Unspecified, treated as unset.
  STORAGE_CLASS_UNSPECIFIED = 0;
  // Append tail latency under 400 milliseconds with s2.dev.
  STORAGE_CLASS_STANDARD = 1;
  // Append tail latency under 40 milliseconds with s2.dev.
  STORAGE_CLASS_EXPRESS = 2;
}

// Timestamping mode for appends that influences how timestamps are handled.
enum TimestampingMode {
  // Unspecified, treated as unset.
  TIMESTAMPING_MODE_UNSPECIFIED = 0;
  // Prefer client-specified timestamp if present otherwise use arrival time.
  TIMESTAMPING_MODE_CLIENT_PREFER = 1;
  // Require a client-specified timestamp and reject the append if it is missing.
  TIMESTAMPING_MODE_CLIENT_REQUIRE = 2;
  // Use the arrival time and ignore any client-specified timestamp.
  TIMESTAMPING_MODE_ARRIVAL = 3;
}

// Timestamping behavior.
message TimestampingConfig {
  // Timestamping mode for appends that influences how timestamps are handled.
  optional TimestampingMode mode = 1;
  // Allow client-specified timestamps to exceed the arrival time.
  // If this is `false` or not set, client timestamps will be capped at the arrival time.
  optional bool uncapped = 2;
}

// Delete-on-empty configuration.
message DeleteOnEmptyConfig {
  // Minimum age in seconds before an empty stream can be deleted.
  // Set to 0 (default) to disable delete-on-empty (don't delete automatically).
  uint64 min_age_secs = 1;
}

// Stream configuration.
// Unset fields inherit from the basin's default stream configuration.
message StreamConfig {
  // Retain records unless explicitly trimmed.
  message InfiniteRetention {}

  // Storage class for recent writes.
  optional StorageClass storage_class = 1;
  // Retention policy for the stream.
  // If unspecified, the default is to retain records for 7 days.
  oneof retention_policy {
    // Age in seconds for automatic trimming of records older than this threshold.
    // This must be set to a value greater than 0 seconds.
    uint64 age = 2;
    // Retain records unless explicitly trimmed.
    InfiniteRetention infinite = 3;
  }
  // Timestamping behavior.
  TimestampingConfig timestamping = 4;
  // Delete-on-empty configuration.
  DeleteOnEmptyConfig delete_on_empty = 5;
}

// Payload of an Append request message.
message AppendInput {
  // Batch of records to append atomically, which must contain at least one record, and no more than 1000.
  // The total size of a batch of records may not exceed 1MiB of metered bytes.
  repeated AppendRecord records = 1;
  // Enforce that the sequence number issued to the first record matches.
  optional uint64 match_seq_num = 2;
  // Enforce a fencing token which must have been previously set by a `fence` command record.
  optional string fencing_token = 3;
  // Stream configuration to apply if this append creates the stream via the basin's `create_stream_on_append` setting.
  // Unset fields inherit the basin's default stream configuration.
  // Ignored if the stream already exists.
  StreamConfig create_stream_config = 4;
}

// Success response message to an Append request.
message AppendAck {
  // Sequence number and timestamp of the first record that was appended.
  StreamPosition start = 1;
  // Sequence number of the last record that was appended + 1, and timestamp of the last record that was appended.
  // The difference between `end.seq_num` and `start.seq_num` will be the number of records appended.
  StreamPosition end = 2;
  // Sequence number that will be assigned to the next record on the stream, and timestamp of the last record on the stream.
  // This can be greater than the `end` position in case of concurrent appends.
  StreamPosition tail = 3;
}

// Record that is durably sequenced on a stream.
message SequencedRecord {
  // Sequence number assigned to this record.
  uint64 seq_num = 1;
  // Timestamp for this record.
  uint64 timestamp = 2;
  // Series of name-value pairs for this record.
  repeated Header headers = 3;
  // Body of this record.
  bytes body = 4;
}

// Success response message to a Read request.
message ReadBatch {
  // Records that are durably sequenced on the stream, retrieved based on the requested criteria.
  // This can only be empty in response to a unary read if the request cannot be satisfied without violating an explicit bound (`count`, `bytes`, or `until`).
  // In the context of a session, it can be empty as a heartbeat message. A heartbeat will be sent whenever a switch to following in real-time happens, and then at a randomized gap between 5 and 15 seconds if no records have become available.
  repeated SequencedRecord records = 1;
  // Sequence number that will be assigned to the next record on the stream, and timestamp of the last record.
  // It will only be present when reading recent records.
  optional StreamPosition tail = 2;
}
